version: '3'

services:
  my-postgres:
    image: postgres:15
    environment:
     - POSTGRES_USER=mercy
     - POSTGRES_PASSWORD=root
     - POSTGRES_DB=todoapp
    ports:
    - '5432:5432'
    volumes:
    - ./pgdata:/var/lib/postgresql/data


  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=development
    depends_on:
      - my-postgres

    
    